### ISSUE TITLE
Larger test corpus

### ISSUE THREAD

**Issue by Insomniak47** [messagetemplates/test-cases#5]
Hey all, I'm implementing message templates at the moment for a few projects with the plan to OSS the implementation and I'm currently writing a bunch of full tests so that I'm confident in it. This test corpus is pretty small - I'm wondering if you had a larger body of tests that you work out of in other contexts? Alternatively if you've got the grammar kicking around in ANTLR I could use it to generate some fuzzing tests.

**Comment by nblumhardt** [comment]
Hi! They may be a bit .NET specific, but checking out the test cases for NLog (github.com/nlog/nlog) and Serilog (github.com/serilog/serilog) may yield some more interesting ones.

I don't have a formal grammar handy, the railroad diagrams from the website should be reasonably straightforward to reverse into one and I'd be happy to help validate it if you decide to have a go.

Keep us posted with progress on your project! :-)

**Comment by Insomniak47** [comment]
Sounds good, I'll try and get it into ANTLR form this weekend. It's been a long time since I've had to look at it and my initial shot failed pretty terribly, haha.

Thanks for the references I'll post something if I manage to succeed this weekend

**Comment by Insomniak47** [comment]
I got distracted with the actual implementation and got it up and running but I did end up writing a bunch more tests by snagging some of serilog's + nlogs & porting them. A question to you re: the implementation. If parsing fails it seems to be implementation dependent how things are treated and I have no strong feelings about it but I was wondering if you had any specific intent/vision?

- Serilog treats holes that can't be parsed as a text token but doesn't do `{{ -> {` token escaping so it's more like a "RawText" but contained in the text token
- nlog throws an exception
- I was planning on returning a parsing failed or giving configuration to treat it as a normal text token (with escaping `{{`), though that would make me less compliant with Serilog. 

Is that something generally you think should be left to implementations or did you have an intent for it originally?

**Comment by nblumhardt** [comment]
Hi! I think treatment of invalid templates was left unspecified because the right behavior depends on the use case.

For application logging, where code paths aren't always tested, failures are problematic, and capturing as much data as possible is worthwhile, Serilog's approach might be preferable.

For situations where correct templates are required for overall application correctness (such as perhaps batch-importing of events?) throwing would be reasonable to me.

Having an API that can communicate parse errors in a non-throwing manner would leave this in the hands of the caller 👍
